// Generated by CoffeeScript 2.3.2
(function() {
  var a, ais, b, blackKeys, c, cis, colorify, d, dis, e, f, fis, g, gis, index, j, key, keyboard, len, names, whiteKeys;

  names = "cdefgab";

  whiteKeys = document.getElementsByClassName("white-key");

  [0];

  blackKeys = document.getElementsByClassName("black-key");

  [0];

  b = whiteKeys[0];

  a = whiteKeys[1];

  g = whiteKeys[2];

  f = whiteKeys[3];

  e = whiteKeys[4];

  d = whiteKeys[5];

  c = whiteKeys[6];

  cis = blackKeys[0];

  dis = blackKeys[1];

  fis = blackKeys[2];

  gis = blackKeys[3];

  ais = blackKeys[4];

  colorify = function(keyColor, key) {
    return key.addEventListener("click", function(e) {
      e.target.style.background = "pink";
      return setTimeout(() => {
        if (keyColor === "black") {
          return e.target.style.background = "black";
        } else {
          return e.target.style.background = "white";
        }
      }, 300);
    });
  };

  keyboard = [a, ais, b, c, cis, d, dis, e, f, fis, g, gis];

  for (index = j = 0, len = keyboard.length; j < len; index = ++j) {
    key = keyboard[index];
    (function(i) {
      if (keyboard[i] === ais || keyboard[i] === cis || keyboard[i] === dis || keyboard[i] === fis || keyboard[i] === gis) {
        colorify("black", key);
        return console.log(key);
      } else {
        return colorify("white", key);
      }
    })(index);
  }

}).call(this);
